// src/views/NewIssue.vue
<template>
  <v-container class="px-md-4 px-lg-5">

    <v-row align="center" justify="center">
        <v-col lg="8">
            <div class="d-flex flex-row">
                <v-text-field
                    outlined
                    dense
                    name="issue-title"
                    label="Title"
                    hide-details="auto"
                    color="white"
                    v-model="issueTitle"
                    @input="updateButtonStatus"
                ></v-text-field>
            </div>
        </v-col>
    </v-row>

    <v-row align="center" justify="center">
        <v-col lg="8">
            <div class="d-flex flex-row">
                <v-textarea
                    @input="updateButtonStatus"
                    v-model="issueText"
                    outlined
                    dense
                    name="issue-text"
                    label="Leave a comment"
                    hide-details="auto"
                    color="white"
                ></v-textarea>
            </div>
        </v-col>
    </v-row>

    <v-row align="center" justify="center">
        <v-col offset-md="10" md="2" offset-lg="6" lg="2">
            <div class="d-flex flex-row">
                <v-text-field
                    outlined
                    dense
                    name="bounty"
                    label="Bounty"
                    hide-details="auto"
                    color="white"
                    v-model="bounty"
                    @input="updateButtonStatus"
                ></v-text-field>
            </div>
        </v-col>
    </v-row>

    <v-row align="center" justify="center">
        <v-col lg="8">
            <div class="d-flex flex-row">
                <v-btn
                    :loading="loading"
                    :disabled="disabled"
                    class="ml-auto"
                    depressed
                    color="green"
                    @click="submitIssue"
                >
                    Submit issue
                </v-btn>
                <v-dialog
                    v-model="dialog"
                    max-width="290"
                >
                    <v-card>
                        <v-card-title class="text-h5">
                        No wallet found
                        </v-card-title>

                        <v-card-text>
                        Connect a wallet in order to submit an issue.
                        </v-card-text>

                        <v-card-actions>
                        <v-spacer></v-spacer>

                        <v-btn
                            color="green darken-1"
                            text
                            @click="dialog = false"
                        >
                            Ok
                        </v-btn>
                        </v-card-actions>
                    </v-card>
                </v-dialog>
            </div>
        </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { ethers } from 'ethers';
import GitRepository from '../utils/GitRepository';

export default {
    name: 'NewIssue',

    props: {
        gitRepo: GitRepository,
    },

    data: () => ({
        issueTitle: '',
        issueText: '',
        bounty: 0,
        disabled: true,
        loading: false,
        dialog: false,
    }),
    methods: {
        async submitIssue() {
            const issue = {
                issueText: this.issueText,
                issueTitle: this.issueTitle,
                timestamp: Date.now(),
            };
            const { web3Provider } = this.$store.state;
            if (web3Provider === null) {
                this.dialog = true;
                return;
            }
            let cid;
            this.gitRepo.web3Signer = web3Provider.getSigner();
            this.$ipfsClient.add(Buffer.from(JSON.stringify(issue)))
                .then((answer) => {
                    cid = answer[0].hash;
                    const overrides = {
                        value: ethers.utils.parseEther(this.bounty.toString()),
                    };
                    return this.gitRepo.openIssue(cid, overrides);
                })
                .then((tx) => {
                    this.loading = true;
                    return tx.wait();
                })
                .then(() => {
                    this.loading = false;
                    return this.gitRepo.web3Signer.getAddress();
                })
                .then((address) => this.gitRepo.getUserCidHash(address, cid))
                .then((result) => this.gitRepo.issue(result[0]))
                .then((newIssue) => {
                    let state;
                    if (newIssue[0].state === 0) {
                        state = 'Open';
                    } else if (newIssue[0].state === 1) {
                        state = 'Closed';
                    } else if (newIssue[0].state === 2) {
                        state = 'Resolved';
                    } else {
                        state = 'Unknown';
                    }
                    const issueData = {
                        state,
                        bounty: ethers.utils.formatEther(newIssue[0].bounty),
                        opener: newIssue[0].opener,
                        title: `#${newIssue[0].issueNumber} ${this.issueTitle}`,
                        text: this.issueText,
                        answers: [],
                        issueNumber: newIssue[0].issueNumber.toString(),
                    };
                    localStorage.setItem('issue', JSON.stringify(issueData));
                    this.$router.push({
                        name: 'Issues',
                        params: {
                            userAddress: this.$router.history.current.params.userAddress,
                            repositoryName: this.$router.history.current.params.repositoryName,
                            action: newIssue[0].issueNumber,
                        },
                    });
                });
        },
        updateButtonStatus() {
            this.disabled = this.issueTitle.length === 0 || this.issueText.length === 0;
        },
    },
};
</script>

// src/pages/Issue/subpages/NewIssue/index.tsx
import { Container, Grid, Paper } from "@mui/material";
import { Button } from "components/Button";
import { TextField } from "components/TextField";
import { WalletContainer } from "containers/WalletContainer";
import React, { useState } from "react";
import { ethers } from "ethers";
import { useForm, Controller } from "react-hook-form";
import { useHistory } from "react-router-dom";
import { NoWalletModal } from "components/NoWalletModal";
import { Transaction } from "interfaces/Transaction";

interface IssueForm {
  title: string;
  comment: string;
  bounty: number;
}

export const NewIssue: React.FC = () => {
  const { gitRepository, web3Provider, repoUrl } =
    WalletContainer.useContainer();

  const [openModal, setOpenModal] = useState(false);
  const handleCloseModal = () => setOpenModal(false);

  const history = useHistory();
  const [loading, setLoading] = useState<boolean>(false);
  const { control, handleSubmit, watch } = useForm<IssueForm>();

  const submitIssue = (form: IssueForm) => {
    const issue = {
      issueText: form.comment,
      issueTitle: form.title,
      timestamp: Date.now(),
    };
    if (web3Provider === "") {
      setOpenModal(true);
      return;
    }
    let cid: string;
    let issueHash: string;
    const gitRepo = gitRepository;
    gitRepo.web3Signer = web3Provider.getSigner();
    fetch("https://api.web3.storage/upload", {
        method: 'POST', 
        headers: new Headers({
            'Authorization': 'Bearer ' + process.env.WEB3_STORAGE_TOKEN, 
            'Content-Type': 'application/json'
        }),
        body: JSON.stringify(issue)
    })
        .then((response: any) => response.json())
        .then((data: any) => {
            cid = data.cid;
            const overrides = {
                value: ethers.utils.parseEther(form.bounty.toString()),
            };
            return gitRepository.openIssue(cid, overrides);
        })
        .then((tx: Transaction) => {
            setLoading(true);
            return tx.wait();
        })
        .then(() => {
            setLoading(false);
            return gitRepository.web3Signer.getAddress();
        })
        .then((address: string) => gitRepository.getUserCidHash(address, cid))
        .then((result: Array<string>) => {
            issueHash = result[0];
            return gitRepository.issue(result[0]);
        })
        .then((newIssue: Array<any>) => {
            let state;
            if (newIssue[0].state === 0) {
              state = "Open";
            } else if (newIssue[0].state === 1) {
              state = "Closed";
            } else if (newIssue[0].state === 2) {
              state = "Resolved";
            } else {
              state = "Unknown";
            }
            const issueData = {
              state,
              bounty: ethers.utils.formatEther(newIssue[0].bounty),
              opener: newIssue[0].opener,
              title: issue.issueTitle,
              text: issue.issueText,
              answers: [],
              issueNumber: newIssue[0].issueNumber.toString(),
              issueHash: issueHash,
            };
            localStorage.setItem("issue", JSON.stringify(issueData));
            history.push(`${repoUrl}/issues/${newIssue[0].issueNumber}`);
        });
  };

  const disableSubmitBtn =
    watch("title") === "" ||
    watch("title") === undefined ||
    watch("comment") === "" ||
    watch("comment") === undefined;

  return (
    <Container>
      <form onSubmit={handleSubmit(submitIssue)}>
        <Grid
          container
          flexDirection="column"
          justifyContent="space-between"
          gap={2}
          marginTop={4}
          marginBottom={2}
          padding={3}
          component={Paper}
        >
          <Grid item>
            <Controller
              name="title"
              control={control}
              defaultValue=""
              render={({ field: { onChange, value } }) => (
                <TextField
                  label="Title"
                  maxRows={4}
                  value={value}
                  onChange={onChange}
                  fullWidth
                />
              )}
            />
          </Grid>
          <Grid item>
            <Controller
              name="comment"
              control={control}
              defaultValue=""
              render={({ field: { onChange, value } }) => (
                <TextField
                  label="Leave a comment"
                  multiline
                  rows={4}
                  fullWidth
                  value={value}
                  onChange={onChange}
                />
              )}
            />
          </Grid>
          <Grid item>
            <Controller
              name="bounty"
              control={control}
              defaultValue={0}
              render={({ field: { onChange, value } }) => (
                <TextField
                  label="Bounty"
                  sx={{ float: "right" }}
                  value={value}
                  onChange={onChange}
                />
              )}
            />
          </Grid>
        </Grid>
        <Button
          label="Submit issue"
          size="small"
          color="secondary"
          variant="contained"
          sx={{ float: "right" }}
          type="submit"
          loading={loading}
          disabled={disableSubmitBtn}
        />
      </form>
      <NoWalletModal
        openModal={openModal}
        handleCloseModal={handleCloseModal}
      />
    </Container>
  );
};
